#' LQC Filteirng
#'
#' Filters out EICs with LQC RSD % above a user provided threshold.
#'
#' @param peakTable peak table generated by xcms group object
#' @param eicColumn name of the EIC column
#' @param lqcColumns names of the LQC columns
#' @param rsdThreshold RSD % threshold for filtering; default 0.3
#'
#' @return peakTable with filtered EICs
#'
#' @examples
#' \donttest{
#'    lqc_filtered_table <- lqcFiltering(peakTable = group_table,
#`                                       eicColumn = "EICNo",
#`                                       lqcColumns = lqcColumns)
#' }
#'
#'  @export


lqcFiltering <- function(peakTable,
                         eicColumn,
                         lqcColumns,
                         rsdThreshold=0.3){


  if(missing(eicColumn) | missing(lqcColumns)){
    stop("One or more of the following arguments are missing values:\neicColumn\nlqcColumns\nsampleColumns")
  }

  if(missing(peakTable)){
    stop("An xcms peak table must be supplied.")
  }

  if(eicColumn %in% colnames(peakTable)==F){
    stop("eicColumn is not present in peak table")
  }

  if(any(lqcColumns %in% colnames(peakTable)==F)){
    stop("One of more of the names in the lqcColumns argument is not present in the peak table")
  }

  if(any(sampleColumns %in% colnames(peakTable)==F)){
    stop("One of more of the names in the sampleColumns argument is not present in the peak table")
  }

  lqc_rsd <- apply(peakTable[,lqcColumns], 1, function(x){sd(x,na.rm=T)/mean(x,na.rm=T)})
  filterTable <- cbind(lqc_rsd = lqc_rsd, peakTable)

  # remove EICs with NA values for RSD of cc Samples
  filter_na_new_pt <- filterTable[!is.na(filterTable$lqc_rsd),]

  filter_rsd_peakTable <- filter_na_new_pt[filter_na_new_pt$lqc_rsd <= rsdThreshold,]

  peakTable <- filter_rsd_peakTable

  return(peakTable)

}
